KERNEL_BUILD_ARCH   = arm64
KERNEL_HEADER_ARCH  = $(KERNEL_BUILD_ARCH)
KERNEL_BUILD_IMAGE  = vmlinuz.efi
KERNEL_IMAGE_PATH   = arch/$(KERNEL_BUILD_ARCH)/boot/$(KERNEL_BUILD_IMAGE)
KERNEL_INSTALL_FILE = vmlinuz
GRUB_RECOMMENDS     = grub-efi-arm64
