#!/bin/bash

usage() {
    echo "USAGE: $0 INFILE OUTFILE [ABI INFILE-IS-DEB]" >&2
    exit 1
}

input_file="$1"
output_file="$2"
abi="$3"
extract_deb="$4"

[ -z "$input_file" ] && usage
[ -z "$output_file" ] && usage
[ ! -e "$input_file" ] && echo "input file '$input_file' does not exist" >&2 && exit 1

if [ -n "$extract_deb" ]; then
    [ -z "$abi" ] && usage
    exec 3< <(dpkg --fsys-tarfile "$input_file" | tar -xOf - "./usr/src/linux-headers-${abi}/Module.symvers")
else
    exec 3< "$input_file"
fi

awk '{
    if (NF >= 3) {
        printf "%s %s ", $NF, $(NF-1)
        for (i = 1; i <= NF-2; i++)
            printf "%s%s", $i, (i < NF-2 ? "\t" : "")
        print ""
    } else {
        print "malformed symvers line: \""$0"\"" > "/dev/stderr"
    }
}' <&3 | sort > "$output_file"

exec 3<&-
